### ISSUE TITLE
Data for Training

### ISSUE THREAD

**Issue by BP-Test** [BP-Test/01_fresh_vegetable_competition#8]
@S10aki95 
As we discussed, I have managed to create the data for training, please find it [here](https://github.com/BP-Test/01_fresh_vegetable_competition/blob/class_preprocess_train/data/model_input_data.csv)

The dataframe is the result of following code
```python
## Run generate_model_data of TrainModel() to create and save a dataframe for modelbuilding

import sys
sys.dont_write_bytecode=True
sys.path.append('../src')

from vege_train import TrainModel

vege = TrainModel()
vege.generate_model_data(file_name='model_input_data')

```
If you specify a parameter, you can generate other types of lag data such as follows

```python

vege.generate_model_data(_lag_list=[1,2,3,6,9,12] file_name='model_input_data_2')


```

Now i think you can start creating your own model, and also instantiate mlflow environment.
Could you do that?

Please close the issue if it looks fine.

**Comment by S10aki95** [comment]
Thanks! I will try it.

**Comment by S10aki95** [comment]
It looks fine, but we need to generalize the process and classify them as methods
